# Generated by Django 4.1.7 on 2023-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='公司名稱')),
                ('job_title', models.CharField(max_length=50, verbose_name='職稱')),
                ('job_cate', models.CharField(max_length=100, verbose_name='職務類別')),
                ('job_salary', models.CharField(max_length=20, verbose_name='薪資')),
                ('job_location', models.CharField(max_length=50, verbose_name='上班地點')),
                ('job_work_experience', models.CharField(max_length=20, verbose_name='工作經歷')),
                ('job_edu_require', models.CharField(max_length=20, verbose_name='學歷要求')),
                ('job_require_major', models.CharField(max_length=100, verbose_name='科系要求')),
                ('job_tool_require', models.TextField(verbose_name='擅長工具')),
                ('job_applicant', models.CharField(max_length=20, verbose_name='應徵人數')),
                ('date', models.CharField(max_length=10, verbose_name='更新日期')),
                ('job_link', models.TextField(verbose_name='連結')),
            ],
            options={
                'verbose_name': '職缺基本資訊',
                'db_table': 'jobbaseinfo',
                'ordering': ['-job_id'],
                'managed': True,
            },
        ),
    ]
