# Generated by Django 4.1.7 on 2023-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='job_location',
            field=models.CharField(max_length=150, verbose_name='上班地點'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='job_salary',
            field=models.CharField(max_length=50, verbose_name='薪資'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='職稱'),
        ),
    ]
