# Generated by Django 4.1.7 on 2023-04-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_alter_baseinfo_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinfo',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='公司名稱'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='職稱'),
        ),
    ]
